
CREATE TABLE security_role (
  ID BIGINT PRIMARY KEY,
  DESCRIPTION VARCHAR(100) DEFAULT NULL,
  ROLE_NAME VARCHAR(100) DEFAULT NULL
);
CREATE SEQUENCE ROLE_SEQ_ID INCREMENT BY 1;

CREATE TABLE security_user (
  ID BIGINT PRIMARY KEY,
  USERNAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255) NOT NULL
);
CREATE SEQUENCE USER_SEQ_ID INCREMENT BY 1;

CREATE TABLE user_role (
  USER_ID BIGINT NOT NULL,
  ROLE_ID BIGINT NOT NULL,
  CONSTRAINT FK_SECURITY_USER_ID FOREIGN KEY (USER_ID) REFERENCES SECURITY_USER (ID),
  CONSTRAINT FK_SECURITY_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES SECURITY_ROLE (ID)
);

CREATE TABLE Person (
  ID BIGINT PRIMARY KEY,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255) NOT NULL,
  AGE INTEGER NOT NULL,
  FAVOURITE_COLOUR VARCHAR(255),
  NATIONALITY VARCHAR(255)
);
ALTER TABLE Person ADD CONSTRAINT NAME_UNIQUE UNIQUE(FIRST_NAME,LAST_NAME);
CREATE SEQUENCE PERSON_SEQ_ID INCREMENT BY 1;
